/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Qase.Client.Client.OpenAPIDateConverter;

namespace Qase.Client.Model
{
    /// <summary>
    /// ResultCreateResponseAllOfResult
    /// </summary>
    [DataContract(Name = "ResultCreateResponse_allOf_result")]
    public partial class ResultCreateResponseAllOfResult
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResultCreateResponseAllOfResult" /> class.
        /// </summary>
        /// <param name="caseId">caseId.</param>
        /// <param name="hash">hash.</param>
        public ResultCreateResponseAllOfResult(long caseId = default(long), string hash = default(string))
        {
            this.CaseId = caseId;
            this.Hash = hash;
        }

        /// <summary>
        /// Gets or Sets CaseId
        /// </summary>
        [DataMember(Name = "case_id", EmitDefaultValue = false)]
        public long CaseId { get; set; }

        /// <summary>
        /// Gets or Sets Hash
        /// </summary>
        [DataMember(Name = "hash", EmitDefaultValue = false)]
        public string Hash { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResultCreateResponseAllOfResult {\n");
            sb.Append("  CaseId: ").Append(CaseId).Append("\n");
            sb.Append("  Hash: ").Append(Hash).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
