/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Qase.Client.Client.OpenAPIDateConverter;

namespace Qase.Client.Model
{
    /// <summary>
    /// RunCreate
    /// </summary>
    [DataContract(Name = "RunCreate")]
    public partial class RunCreate
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RunCreate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RunCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RunCreate" /> class.
        /// </summary>
        /// <param name="title">title (required).</param>
        /// <param name="description">description.</param>
        /// <param name="includeAllCases">includeAllCases.</param>
        /// <param name="cases">cases.</param>
        /// <param name="isAutotest">isAutotest.</param>
        /// <param name="environmentId">environmentId.</param>
        /// <param name="environmentSlug">environmentSlug.</param>
        /// <param name="milestoneId">milestoneId.</param>
        /// <param name="planId">planId.</param>
        /// <param name="authorId">authorId.</param>
        /// <param name="tags">tags.</param>
        /// <param name="configurations">configurations.</param>
        /// <param name="customField">A map of custom fields values (id &#x3D;&gt; value).</param>
        /// <param name="startTime">startTime.</param>
        /// <param name="endTime">endTime.</param>
        public RunCreate(string title = default(string), string description = default(string), bool includeAllCases = default(bool), List<long> cases = default(List<long>), bool isAutotest = default(bool), long environmentId = default(long), string environmentSlug = default(string), long milestoneId = default(long), long planId = default(long), long authorId = default(long), List<string> tags = default(List<string>), List<long> configurations = default(List<long>), Dictionary<string, string> customField = default(Dictionary<string, string>), string startTime = default(string), string endTime = default(string))
        {
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for RunCreate and cannot be null");
            }
            this.Title = title;
            this.Description = description;
            this.IncludeAllCases = includeAllCases;
            this.Cases = cases;
            this.IsAutotest = isAutotest;
            this.EnvironmentId = environmentId;
            this.EnvironmentSlug = environmentSlug;
            this.MilestoneId = milestoneId;
            this.PlanId = planId;
            this.AuthorId = authorId;
            this.Tags = tags;
            this.Configurations = configurations;
            this.CustomField = customField;
            this.StartTime = startTime;
            this.EndTime = endTime;
        }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets IncludeAllCases
        /// </summary>
        [DataMember(Name = "include_all_cases", EmitDefaultValue = true)]
        public bool IncludeAllCases { get; set; }

        /// <summary>
        /// Gets or Sets Cases
        /// </summary>
        [DataMember(Name = "cases", EmitDefaultValue = false)]
        public List<long> Cases { get; set; }

        /// <summary>
        /// Gets or Sets IsAutotest
        /// </summary>
        [DataMember(Name = "is_autotest", EmitDefaultValue = true)]
        public bool IsAutotest { get; set; }

        /// <summary>
        /// Gets or Sets EnvironmentId
        /// </summary>
        [DataMember(Name = "environment_id", EmitDefaultValue = false)]
        public long EnvironmentId { get; set; }

        /// <summary>
        /// Gets or Sets EnvironmentSlug
        /// </summary>
        [DataMember(Name = "environment_slug", EmitDefaultValue = false)]
        public string EnvironmentSlug { get; set; }

        /// <summary>
        /// Gets or Sets MilestoneId
        /// </summary>
        [DataMember(Name = "milestone_id", EmitDefaultValue = false)]
        public long MilestoneId { get; set; }

        /// <summary>
        /// Gets or Sets PlanId
        /// </summary>
        [DataMember(Name = "plan_id", EmitDefaultValue = false)]
        public long PlanId { get; set; }

        /// <summary>
        /// Gets or Sets AuthorId
        /// </summary>
        [DataMember(Name = "author_id", EmitDefaultValue = false)]
        public long AuthorId { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [DataMember(Name = "tags", EmitDefaultValue = false)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Gets or Sets Configurations
        /// </summary>
        [DataMember(Name = "configurations", EmitDefaultValue = false)]
        public List<long> Configurations { get; set; }

        /// <summary>
        /// A map of custom fields values (id &#x3D;&gt; value)
        /// </summary>
        /// <value>A map of custom fields values (id &#x3D;&gt; value)</value>
        [DataMember(Name = "custom_field", EmitDefaultValue = false)]
        public Dictionary<string, string> CustomField { get; set; }

        /// <summary>
        /// Gets or Sets StartTime
        /// </summary>
        [DataMember(Name = "start_time", EmitDefaultValue = false)]
        public string StartTime { get; set; }

        /// <summary>
        /// Gets or Sets EndTime
        /// </summary>
        [DataMember(Name = "end_time", EmitDefaultValue = false)]
        public string EndTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RunCreate {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  IncludeAllCases: ").Append(IncludeAllCases).Append("\n");
            sb.Append("  Cases: ").Append(Cases).Append("\n");
            sb.Append("  IsAutotest: ").Append(IsAutotest).Append("\n");
            sb.Append("  EnvironmentId: ").Append(EnvironmentId).Append("\n");
            sb.Append("  EnvironmentSlug: ").Append(EnvironmentSlug).Append("\n");
            sb.Append("  MilestoneId: ").Append(MilestoneId).Append("\n");
            sb.Append("  PlanId: ").Append(PlanId).Append("\n");
            sb.Append("  AuthorId: ").Append(AuthorId).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Configurations: ").Append(Configurations).Append("\n");
            sb.Append("  CustomField: ").Append(CustomField).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
