/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Qase.Client.Client.OpenAPIDateConverter;

namespace Qase.Client.Model
{
    /// <summary>
    /// RunStats
    /// </summary>
    [DataContract(Name = "Run_stats")]
    public partial class RunStats
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RunStats" /> class.
        /// </summary>
        /// <param name="total">total.</param>
        /// <param name="statuses">statuses.</param>
        /// <param name="untested">untested.</param>
        /// <param name="passed">passed.</param>
        /// <param name="failed">failed.</param>
        /// <param name="blocked">blocked.</param>
        /// <param name="skipped">skipped.</param>
        /// <param name="retest">retest.</param>
        /// <param name="inProgress">inProgress.</param>
        /// <param name="invalid">invalid.</param>
        public RunStats(int total = default(int), Dictionary<string, int> statuses = default(Dictionary<string, int>), int untested = default(int), int passed = default(int), int failed = default(int), int blocked = default(int), int skipped = default(int), int retest = default(int), int inProgress = default(int), int invalid = default(int))
        {
            this.Total = total;
            this.Statuses = statuses;
            this.Untested = untested;
            this.Passed = passed;
            this.Failed = failed;
            this.Blocked = blocked;
            this.Skipped = skipped;
            this.Retest = retest;
            this.InProgress = inProgress;
            this.Invalid = invalid;
        }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [DataMember(Name = "total", EmitDefaultValue = false)]
        public int Total { get; set; }

        /// <summary>
        /// Gets or Sets Statuses
        /// </summary>
        [DataMember(Name = "statuses", EmitDefaultValue = false)]
        public Dictionary<string, int> Statuses { get; set; }

        /// <summary>
        /// Gets or Sets Untested
        /// </summary>
        [DataMember(Name = "untested", EmitDefaultValue = false)]
        [Obsolete]
        public int Untested { get; set; }

        /// <summary>
        /// Gets or Sets Passed
        /// </summary>
        [DataMember(Name = "passed", EmitDefaultValue = false)]
        [Obsolete]
        public int Passed { get; set; }

        /// <summary>
        /// Gets or Sets Failed
        /// </summary>
        [DataMember(Name = "failed", EmitDefaultValue = false)]
        [Obsolete]
        public int Failed { get; set; }

        /// <summary>
        /// Gets or Sets Blocked
        /// </summary>
        [DataMember(Name = "blocked", EmitDefaultValue = false)]
        [Obsolete]
        public int Blocked { get; set; }

        /// <summary>
        /// Gets or Sets Skipped
        /// </summary>
        [DataMember(Name = "skipped", EmitDefaultValue = false)]
        [Obsolete]
        public int Skipped { get; set; }

        /// <summary>
        /// Gets or Sets Retest
        /// </summary>
        [DataMember(Name = "retest", EmitDefaultValue = false)]
        [Obsolete]
        public int Retest { get; set; }

        /// <summary>
        /// Gets or Sets InProgress
        /// </summary>
        [DataMember(Name = "in_progress", EmitDefaultValue = false)]
        [Obsolete]
        public int InProgress { get; set; }

        /// <summary>
        /// Gets or Sets Invalid
        /// </summary>
        [DataMember(Name = "invalid", EmitDefaultValue = false)]
        [Obsolete]
        public int Invalid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RunStats {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Statuses: ").Append(Statuses).Append("\n");
            sb.Append("  Untested: ").Append(Untested).Append("\n");
            sb.Append("  Passed: ").Append(Passed).Append("\n");
            sb.Append("  Failed: ").Append(Failed).Append("\n");
            sb.Append("  Blocked: ").Append(Blocked).Append("\n");
            sb.Append("  Skipped: ").Append(Skipped).Append("\n");
            sb.Append("  Retest: ").Append(Retest).Append("\n");
            sb.Append("  InProgress: ").Append(InProgress).Append("\n");
            sb.Append("  Invalid: ").Append(Invalid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
