/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Qase.Client.Client.OpenAPIDateConverter;

namespace Qase.Client.Model
{
    /// <summary>
    /// SearchResponseAllOfResult
    /// </summary>
    [DataContract(Name = "SearchResponse_allOf_result")]
    public partial class SearchResponseAllOfResult
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchResponseAllOfResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SearchResponseAllOfResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchResponseAllOfResult" /> class.
        /// </summary>
        /// <param name="entities">entities (required).</param>
        /// <param name="total">total (required).</param>
        public SearchResponseAllOfResult(List<SearchResponseAllOfResultEntities> entities = default(List<SearchResponseAllOfResultEntities>), int total = default(int))
        {
            // to ensure "entities" is required (not null)
            if (entities == null)
            {
                throw new ArgumentNullException("entities is a required property for SearchResponseAllOfResult and cannot be null");
            }
            this.Entities = entities;
            this.Total = total;
        }

        /// <summary>
        /// Gets or Sets Entities
        /// </summary>
        [DataMember(Name = "entities", IsRequired = true, EmitDefaultValue = true)]
        public List<SearchResponseAllOfResultEntities> Entities { get; set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public int Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchResponseAllOfResult {\n");
            sb.Append("  Entities: ").Append(Entities).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
