/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Qase.Client.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Qase.Client.Model
{
    /// <summary>
    /// SearchResponseAllOfResultEntities
    /// </summary>
    [JsonConverter(typeof(SearchResponseAllOfResultEntitiesJsonConverter))]
    [DataContract(Name = "SearchResponse_allOf_result_entities")]
    public partial class SearchResponseAllOfResultEntities : AbstractOpenAPISchema
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchResponseAllOfResultEntities" /> class
        /// with the <see cref="Run" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Run.</param>
        public SearchResponseAllOfResultEntities(Run actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchResponseAllOfResultEntities" /> class
        /// with the <see cref="Result" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Result.</param>
        public SearchResponseAllOfResultEntities(Result actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchResponseAllOfResultEntities" /> class
        /// with the <see cref="Requirement" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Requirement.</param>
        public SearchResponseAllOfResultEntities(Requirement actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchResponseAllOfResultEntities" /> class
        /// with the <see cref="TestCaseQuery" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of TestCaseQuery.</param>
        public SearchResponseAllOfResultEntities(TestCaseQuery actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchResponseAllOfResultEntities" /> class
        /// with the <see cref="DefectQuery" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of DefectQuery.</param>
        public SearchResponseAllOfResultEntities(DefectQuery actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchResponseAllOfResultEntities" /> class
        /// with the <see cref="PlanQuery" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of PlanQuery.</param>
        public SearchResponseAllOfResultEntities(PlanQuery actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(DefectQuery) || value is DefectQuery)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(PlanQuery) || value is PlanQuery)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(Requirement) || value is Requirement)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(Result) || value is Result)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(Run) || value is Run)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(TestCaseQuery) || value is TestCaseQuery)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: DefectQuery, PlanQuery, Requirement, Result, Run, TestCaseQuery");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `Run`. If the actual instance is not `Run`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Run</returns>
        public Run GetRun()
        {
            return (Run)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `Result`. If the actual instance is not `Result`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Result</returns>
        public Result GetResult()
        {
            return (Result)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `Requirement`. If the actual instance is not `Requirement`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Requirement</returns>
        public Requirement GetRequirement()
        {
            return (Requirement)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `TestCaseQuery`. If the actual instance is not `TestCaseQuery`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of TestCaseQuery</returns>
        public TestCaseQuery GetTestCaseQuery()
        {
            return (TestCaseQuery)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `DefectQuery`. If the actual instance is not `DefectQuery`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of DefectQuery</returns>
        public DefectQuery GetDefectQuery()
        {
            return (DefectQuery)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `PlanQuery`. If the actual instance is not `PlanQuery`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of PlanQuery</returns>
        public PlanQuery GetPlanQuery()
        {
            return (PlanQuery)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SearchResponseAllOfResultEntities {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, SearchResponseAllOfResultEntities.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of SearchResponseAllOfResultEntities
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of SearchResponseAllOfResultEntities</returns>
        public static SearchResponseAllOfResultEntities FromJson(string jsonString)
        {
            SearchResponseAllOfResultEntities newSearchResponseAllOfResultEntities = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newSearchResponseAllOfResultEntities;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(DefectQuery).GetProperty("AdditionalProperties") == null)
                {
                    newSearchResponseAllOfResultEntities = new SearchResponseAllOfResultEntities(JsonConvert.DeserializeObject<DefectQuery>(jsonString, SearchResponseAllOfResultEntities.SerializerSettings));
                }
                else
                {
                    newSearchResponseAllOfResultEntities = new SearchResponseAllOfResultEntities(JsonConvert.DeserializeObject<DefectQuery>(jsonString, SearchResponseAllOfResultEntities.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("DefectQuery");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into DefectQuery: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(PlanQuery).GetProperty("AdditionalProperties") == null)
                {
                    newSearchResponseAllOfResultEntities = new SearchResponseAllOfResultEntities(JsonConvert.DeserializeObject<PlanQuery>(jsonString, SearchResponseAllOfResultEntities.SerializerSettings));
                }
                else
                {
                    newSearchResponseAllOfResultEntities = new SearchResponseAllOfResultEntities(JsonConvert.DeserializeObject<PlanQuery>(jsonString, SearchResponseAllOfResultEntities.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("PlanQuery");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into PlanQuery: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(Requirement).GetProperty("AdditionalProperties") == null)
                {
                    newSearchResponseAllOfResultEntities = new SearchResponseAllOfResultEntities(JsonConvert.DeserializeObject<Requirement>(jsonString, SearchResponseAllOfResultEntities.SerializerSettings));
                }
                else
                {
                    newSearchResponseAllOfResultEntities = new SearchResponseAllOfResultEntities(JsonConvert.DeserializeObject<Requirement>(jsonString, SearchResponseAllOfResultEntities.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("Requirement");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Requirement: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(Result).GetProperty("AdditionalProperties") == null)
                {
                    newSearchResponseAllOfResultEntities = new SearchResponseAllOfResultEntities(JsonConvert.DeserializeObject<Result>(jsonString, SearchResponseAllOfResultEntities.SerializerSettings));
                }
                else
                {
                    newSearchResponseAllOfResultEntities = new SearchResponseAllOfResultEntities(JsonConvert.DeserializeObject<Result>(jsonString, SearchResponseAllOfResultEntities.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("Result");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Result: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(Run).GetProperty("AdditionalProperties") == null)
                {
                    newSearchResponseAllOfResultEntities = new SearchResponseAllOfResultEntities(JsonConvert.DeserializeObject<Run>(jsonString, SearchResponseAllOfResultEntities.SerializerSettings));
                }
                else
                {
                    newSearchResponseAllOfResultEntities = new SearchResponseAllOfResultEntities(JsonConvert.DeserializeObject<Run>(jsonString, SearchResponseAllOfResultEntities.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("Run");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Run: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(TestCaseQuery).GetProperty("AdditionalProperties") == null)
                {
                    newSearchResponseAllOfResultEntities = new SearchResponseAllOfResultEntities(JsonConvert.DeserializeObject<TestCaseQuery>(jsonString, SearchResponseAllOfResultEntities.SerializerSettings));
                }
                else
                {
                    newSearchResponseAllOfResultEntities = new SearchResponseAllOfResultEntities(JsonConvert.DeserializeObject<TestCaseQuery>(jsonString, SearchResponseAllOfResultEntities.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("TestCaseQuery");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into TestCaseQuery: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newSearchResponseAllOfResultEntities;
        }

    }

    /// <summary>
    /// Custom JSON converter for SearchResponseAllOfResultEntities
    /// </summary>
    public class SearchResponseAllOfResultEntitiesJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(SearchResponseAllOfResultEntities).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return SearchResponseAllOfResultEntities.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return SearchResponseAllOfResultEntities.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
