/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Qase.Client.Client.OpenAPIDateConverter;

namespace Qase.Client.Model
{
    /// <summary>
    /// SuiteUpdate
    /// </summary>
    [DataContract(Name = "SuiteUpdate")]
    public partial class SuiteUpdate
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SuiteUpdate" /> class.
        /// </summary>
        /// <param name="title">Test suite title..</param>
        /// <param name="description">Test suite description..</param>
        /// <param name="preconditions">Test suite preconditions.</param>
        /// <param name="parentId">Parent suite ID.</param>
        public SuiteUpdate(string title = default(string), string description = default(string), string preconditions = default(string), long? parentId = default(long?))
        {
            this.Title = title;
            this.Description = description;
            this.Preconditions = preconditions;
            this.ParentId = parentId;
        }

        /// <summary>
        /// Test suite title.
        /// </summary>
        /// <value>Test suite title.</value>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// Test suite description.
        /// </summary>
        /// <value>Test suite description.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Test suite preconditions
        /// </summary>
        /// <value>Test suite preconditions</value>
        [DataMember(Name = "preconditions", EmitDefaultValue = false)]
        public string Preconditions { get; set; }

        /// <summary>
        /// Parent suite ID
        /// </summary>
        /// <value>Parent suite ID</value>
        [DataMember(Name = "parent_id", EmitDefaultValue = true)]
        public long? ParentId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SuiteUpdate {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Preconditions: ").Append(Preconditions).Append("\n");
            sb.Append("  ParentId: ").Append(ParentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
