/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Qase.Client.Client.OpenAPIDateConverter;

namespace Qase.Client.Model
{
    /// <summary>
    /// TestCaseexternalIssues
    /// </summary>
    [DataContract(Name = "TestCaseexternal_issues")]
    public partial class TestCaseexternalIssues
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Cloud for value: jira-cloud
            /// </summary>
            [EnumMember(Value = "jira-cloud")]
            Cloud = 1,

            /// <summary>
            /// Enum Server for value: jira-server
            /// </summary>
            [EnumMember(Value = "jira-server")]
            Server = 2
        }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestCaseexternalIssues" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TestCaseexternalIssues() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestCaseexternalIssues" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="links">links (required).</param>
        public TestCaseexternalIssues(TypeEnum type = default(TypeEnum), List<TestCaseExternalIssuesLinksInner> links = default(List<TestCaseExternalIssuesLinksInner>))
        {
            this.Type = type;
            // to ensure "links" is required (not null)
            if (links == null)
            {
                throw new ArgumentNullException("links is a required property for TestCaseexternalIssues and cannot be null");
            }
            this.Links = links;
        }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "links", IsRequired = true, EmitDefaultValue = true)]
        public List<TestCaseExternalIssuesLinksInner> Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TestCaseexternalIssues {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
