/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Qase.Client.Client.OpenAPIDateConverter;

namespace Qase.Client.Model
{
    /// <summary>
    /// TestCasebulk
    /// </summary>
    [DataContract(Name = "TestCasebulk")]
    public partial class TestCasebulk
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestCasebulk" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TestCasebulk() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestCasebulk" /> class.
        /// </summary>
        /// <param name="cases">cases (required).</param>
        public TestCasebulk(List<TestCasebulkCasesInner> cases = default(List<TestCasebulkCasesInner>))
        {
            // to ensure "cases" is required (not null)
            if (cases == null)
            {
                throw new ArgumentNullException("cases is a required property for TestCasebulk and cannot be null");
            }
            this.Cases = cases;
        }

        /// <summary>
        /// Gets or Sets Cases
        /// </summary>
        [DataMember(Name = "cases", IsRequired = true, EmitDefaultValue = true)]
        public List<TestCasebulkCasesInner> Cases { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TestCasebulk {\n");
            sb.Append("  Cases: ").Append(Cases).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
