/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Qase.Client.Client;
using Qase.Client.Model;

namespace Qase.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IConfigurationsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a new configuration in a particular group.
        /// </summary>
        /// <remarks>
        /// This method allows to create a configuration in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdResponse</returns>
        IdResponse CreateConfiguration(string code, ConfigurationCreate configurationCreate, int operationIndex = 0);

        /// <summary>
        /// Create a new configuration in a particular group.
        /// </summary>
        /// <remarks>
        /// This method allows to create a configuration in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdResponse</returns>
        ApiResponse<IdResponse> CreateConfigurationWithHttpInfo(string code, ConfigurationCreate configurationCreate, int operationIndex = 0);
        /// <summary>
        /// Create a new configuration group.
        /// </summary>
        /// <remarks>
        /// This method allows to create a configuration group in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationGroupCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdResponse</returns>
        IdResponse CreateConfigurationGroup(string code, ConfigurationGroupCreate configurationGroupCreate, int operationIndex = 0);

        /// <summary>
        /// Create a new configuration group.
        /// </summary>
        /// <remarks>
        /// This method allows to create a configuration group in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationGroupCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdResponse</returns>
        ApiResponse<IdResponse> CreateConfigurationGroupWithHttpInfo(string code, ConfigurationGroupCreate configurationGroupCreate, int operationIndex = 0);
        /// <summary>
        /// Get all configuration groups with configurations.
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all configurations groups with configurations 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConfigurationListResponse</returns>
        ConfigurationListResponse GetConfigurations(string code, int operationIndex = 0);

        /// <summary>
        /// Get all configuration groups with configurations.
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all configurations groups with configurations 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConfigurationListResponse</returns>
        ApiResponse<ConfigurationListResponse> GetConfigurationsWithHttpInfo(string code, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IConfigurationsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create a new configuration in a particular group.
        /// </summary>
        /// <remarks>
        /// This method allows to create a configuration in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdResponse</returns>
        System.Threading.Tasks.Task<IdResponse> CreateConfigurationAsync(string code, ConfigurationCreate configurationCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Create a new configuration in a particular group.
        /// </summary>
        /// <remarks>
        /// This method allows to create a configuration in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<IdResponse>> CreateConfigurationWithHttpInfoAsync(string code, ConfigurationCreate configurationCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Create a new configuration group.
        /// </summary>
        /// <remarks>
        /// This method allows to create a configuration group in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationGroupCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdResponse</returns>
        System.Threading.Tasks.Task<IdResponse> CreateConfigurationGroupAsync(string code, ConfigurationGroupCreate configurationGroupCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Create a new configuration group.
        /// </summary>
        /// <remarks>
        /// This method allows to create a configuration group in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationGroupCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<IdResponse>> CreateConfigurationGroupWithHttpInfoAsync(string code, ConfigurationGroupCreate configurationGroupCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get all configuration groups with configurations.
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all configurations groups with configurations 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConfigurationListResponse</returns>
        System.Threading.Tasks.Task<ConfigurationListResponse> GetConfigurationsAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get all configuration groups with configurations.
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all configurations groups with configurations 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConfigurationListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ConfigurationListResponse>> GetConfigurationsWithHttpInfoAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IConfigurationsApi : IConfigurationsApiSync, IConfigurationsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ConfigurationsApi : IConfigurationsApi
    {
        private Qase.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ConfigurationsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ConfigurationsApi(string basePath)
        {
            this.Configuration = Qase.Client.Client.Configuration.MergeConfigurations(
                Qase.Client.Client.GlobalConfiguration.Instance,
                new Qase.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Qase.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ConfigurationsApi(Qase.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Qase.Client.Client.Configuration.MergeConfigurations(
                Qase.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Qase.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ConfigurationsApi(Qase.Client.Client.ISynchronousClient client, Qase.Client.Client.IAsynchronousClient asyncClient, Qase.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Qase.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Qase.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Qase.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Qase.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Qase.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create a new configuration in a particular group. This method allows to create a configuration in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdResponse</returns>
        public IdResponse CreateConfiguration(string code, ConfigurationCreate configurationCreate, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<IdResponse> localVarResponse = CreateConfigurationWithHttpInfo(code, configurationCreate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new configuration in a particular group. This method allows to create a configuration in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdResponse</returns>
        public Qase.Client.Client.ApiResponse<IdResponse> CreateConfigurationWithHttpInfo(string code, ConfigurationCreate configurationCreate, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ConfigurationsApi->CreateConfiguration");
            }

            // verify the required parameter 'configurationCreate' is set
            if (configurationCreate == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'configurationCreate' when calling ConfigurationsApi->CreateConfiguration");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = configurationCreate;

            localVarRequestOptions.Operation = "ConfigurationsApi.CreateConfiguration";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<IdResponse>("/configuration/{code}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateConfiguration", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new configuration in a particular group. This method allows to create a configuration in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdResponse</returns>
        public async System.Threading.Tasks.Task<IdResponse> CreateConfigurationAsync(string code, ConfigurationCreate configurationCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<IdResponse> localVarResponse = await CreateConfigurationWithHttpInfoAsync(code, configurationCreate, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new configuration in a particular group. This method allows to create a configuration in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<IdResponse>> CreateConfigurationWithHttpInfoAsync(string code, ConfigurationCreate configurationCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ConfigurationsApi->CreateConfiguration");
            }

            // verify the required parameter 'configurationCreate' is set
            if (configurationCreate == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'configurationCreate' when calling ConfigurationsApi->CreateConfiguration");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = configurationCreate;

            localVarRequestOptions.Operation = "ConfigurationsApi.CreateConfiguration";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<IdResponse>("/configuration/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateConfiguration", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new configuration group. This method allows to create a configuration group in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationGroupCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdResponse</returns>
        public IdResponse CreateConfigurationGroup(string code, ConfigurationGroupCreate configurationGroupCreate, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<IdResponse> localVarResponse = CreateConfigurationGroupWithHttpInfo(code, configurationGroupCreate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new configuration group. This method allows to create a configuration group in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationGroupCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdResponse</returns>
        public Qase.Client.Client.ApiResponse<IdResponse> CreateConfigurationGroupWithHttpInfo(string code, ConfigurationGroupCreate configurationGroupCreate, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ConfigurationsApi->CreateConfigurationGroup");
            }

            // verify the required parameter 'configurationGroupCreate' is set
            if (configurationGroupCreate == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'configurationGroupCreate' when calling ConfigurationsApi->CreateConfigurationGroup");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = configurationGroupCreate;

            localVarRequestOptions.Operation = "ConfigurationsApi.CreateConfigurationGroup";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<IdResponse>("/configuration/{code}/group", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateConfigurationGroup", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new configuration group. This method allows to create a configuration group in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationGroupCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdResponse</returns>
        public async System.Threading.Tasks.Task<IdResponse> CreateConfigurationGroupAsync(string code, ConfigurationGroupCreate configurationGroupCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<IdResponse> localVarResponse = await CreateConfigurationGroupWithHttpInfoAsync(code, configurationGroupCreate, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new configuration group. This method allows to create a configuration group in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="configurationGroupCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<IdResponse>> CreateConfigurationGroupWithHttpInfoAsync(string code, ConfigurationGroupCreate configurationGroupCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ConfigurationsApi->CreateConfigurationGroup");
            }

            // verify the required parameter 'configurationGroupCreate' is set
            if (configurationGroupCreate == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'configurationGroupCreate' when calling ConfigurationsApi->CreateConfigurationGroup");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = configurationGroupCreate;

            localVarRequestOptions.Operation = "ConfigurationsApi.CreateConfigurationGroup";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<IdResponse>("/configuration/{code}/group", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateConfigurationGroup", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all configuration groups with configurations. This method allows to retrieve all configurations groups with configurations 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConfigurationListResponse</returns>
        public ConfigurationListResponse GetConfigurations(string code, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<ConfigurationListResponse> localVarResponse = GetConfigurationsWithHttpInfo(code);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all configuration groups with configurations. This method allows to retrieve all configurations groups with configurations 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConfigurationListResponse</returns>
        public Qase.Client.Client.ApiResponse<ConfigurationListResponse> GetConfigurationsWithHttpInfo(string code, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ConfigurationsApi->GetConfigurations");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter

            localVarRequestOptions.Operation = "ConfigurationsApi.GetConfigurations";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ConfigurationListResponse>("/configuration/{code}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetConfigurations", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all configuration groups with configurations. This method allows to retrieve all configurations groups with configurations 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConfigurationListResponse</returns>
        public async System.Threading.Tasks.Task<ConfigurationListResponse> GetConfigurationsAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<ConfigurationListResponse> localVarResponse = await GetConfigurationsWithHttpInfoAsync(code, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all configuration groups with configurations. This method allows to retrieve all configurations groups with configurations 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConfigurationListResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<ConfigurationListResponse>> GetConfigurationsWithHttpInfoAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ConfigurationsApi->GetConfigurations");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter

            localVarRequestOptions.Operation = "ConfigurationsApi.GetConfigurations";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ConfigurationListResponse>("/configuration/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetConfigurations", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
