/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Qase.Client.Client;
using Qase.Client.Model;

namespace Qase.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProjectsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create new project
        /// </summary>
        /// <remarks>
        /// This method is used to create a new project through API. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ProjectCodeResponse</returns>
        ProjectCodeResponse CreateProject(ProjectCreate projectCreate, int operationIndex = 0);

        /// <summary>
        /// Create new project
        /// </summary>
        /// <remarks>
        /// This method is used to create a new project through API. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ProjectCodeResponse</returns>
        ApiResponse<ProjectCodeResponse> CreateProjectWithHttpInfo(ProjectCreate projectCreate, int operationIndex = 0);
        /// <summary>
        /// Delete Project by code
        /// </summary>
        /// <remarks>
        /// This method allows to delete a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BaseResponse</returns>
        BaseResponse DeleteProject(string code, int operationIndex = 0);

        /// <summary>
        /// Delete Project by code
        /// </summary>
        /// <remarks>
        /// This method allows to delete a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BaseResponse</returns>
        ApiResponse<BaseResponse> DeleteProjectWithHttpInfo(string code, int operationIndex = 0);
        /// <summary>
        /// Get Project by code
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ProjectResponse</returns>
        ProjectResponse GetProject(string code, int operationIndex = 0);

        /// <summary>
        /// Get Project by code
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ProjectResponse</returns>
        ApiResponse<ProjectResponse> GetProjectWithHttpInfo(string code, int operationIndex = 0);
        /// <summary>
        /// Get All Projects
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all projects available for your account. You can limit and offset params to paginate. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ProjectListResponse</returns>
        ProjectListResponse GetProjects(int? limit = default(int?), int? offset = default(int?), int operationIndex = 0);

        /// <summary>
        /// Get All Projects
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all projects available for your account. You can limit and offset params to paginate. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ProjectListResponse</returns>
        ApiResponse<ProjectListResponse> GetProjectsWithHttpInfo(int? limit = default(int?), int? offset = default(int?), int operationIndex = 0);
        /// <summary>
        /// Grant access to project by code
        /// </summary>
        /// <remarks>
        /// This method allows to grant access to a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BaseResponse</returns>
        BaseResponse GrantAccessToProject(string code, ProjectAccess projectAccess, int operationIndex = 0);

        /// <summary>
        /// Grant access to project by code
        /// </summary>
        /// <remarks>
        /// This method allows to grant access to a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BaseResponse</returns>
        ApiResponse<BaseResponse> GrantAccessToProjectWithHttpInfo(string code, ProjectAccess projectAccess, int operationIndex = 0);
        /// <summary>
        /// Revoke access to project by code
        /// </summary>
        /// <remarks>
        /// This method allows to revoke access to a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BaseResponse</returns>
        BaseResponse RevokeAccessToProject(string code, ProjectAccess projectAccess, int operationIndex = 0);

        /// <summary>
        /// Revoke access to project by code
        /// </summary>
        /// <remarks>
        /// This method allows to revoke access to a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BaseResponse</returns>
        ApiResponse<BaseResponse> RevokeAccessToProjectWithHttpInfo(string code, ProjectAccess projectAccess, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProjectsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create new project
        /// </summary>
        /// <remarks>
        /// This method is used to create a new project through API. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProjectCodeResponse</returns>
        System.Threading.Tasks.Task<ProjectCodeResponse> CreateProjectAsync(ProjectCreate projectCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Create new project
        /// </summary>
        /// <remarks>
        /// This method is used to create a new project through API. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProjectCodeResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ProjectCodeResponse>> CreateProjectWithHttpInfoAsync(ProjectCreate projectCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Delete Project by code
        /// </summary>
        /// <remarks>
        /// This method allows to delete a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BaseResponse</returns>
        System.Threading.Tasks.Task<BaseResponse> DeleteProjectAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Delete Project by code
        /// </summary>
        /// <remarks>
        /// This method allows to delete a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BaseResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BaseResponse>> DeleteProjectWithHttpInfoAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get Project by code
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProjectResponse</returns>
        System.Threading.Tasks.Task<ProjectResponse> GetProjectAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get Project by code
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProjectResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ProjectResponse>> GetProjectWithHttpInfoAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get All Projects
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all projects available for your account. You can limit and offset params to paginate. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProjectListResponse</returns>
        System.Threading.Tasks.Task<ProjectListResponse> GetProjectsAsync(int? limit = default(int?), int? offset = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get All Projects
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all projects available for your account. You can limit and offset params to paginate. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProjectListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ProjectListResponse>> GetProjectsWithHttpInfoAsync(int? limit = default(int?), int? offset = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Grant access to project by code
        /// </summary>
        /// <remarks>
        /// This method allows to grant access to a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BaseResponse</returns>
        System.Threading.Tasks.Task<BaseResponse> GrantAccessToProjectAsync(string code, ProjectAccess projectAccess, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Grant access to project by code
        /// </summary>
        /// <remarks>
        /// This method allows to grant access to a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BaseResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BaseResponse>> GrantAccessToProjectWithHttpInfoAsync(string code, ProjectAccess projectAccess, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Revoke access to project by code
        /// </summary>
        /// <remarks>
        /// This method allows to revoke access to a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BaseResponse</returns>
        System.Threading.Tasks.Task<BaseResponse> RevokeAccessToProjectAsync(string code, ProjectAccess projectAccess, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Revoke access to project by code
        /// </summary>
        /// <remarks>
        /// This method allows to revoke access to a specific project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BaseResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BaseResponse>> RevokeAccessToProjectWithHttpInfoAsync(string code, ProjectAccess projectAccess, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProjectsApi : IProjectsApiSync, IProjectsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ProjectsApi : IProjectsApi
    {
        private Qase.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ProjectsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ProjectsApi(string basePath)
        {
            this.Configuration = Qase.Client.Client.Configuration.MergeConfigurations(
                Qase.Client.Client.GlobalConfiguration.Instance,
                new Qase.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Qase.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ProjectsApi(Qase.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Qase.Client.Client.Configuration.MergeConfigurations(
                Qase.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Qase.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ProjectsApi(Qase.Client.Client.ISynchronousClient client, Qase.Client.Client.IAsynchronousClient asyncClient, Qase.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Qase.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Qase.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Qase.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Qase.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Qase.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create new project This method is used to create a new project through API. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ProjectCodeResponse</returns>
        public ProjectCodeResponse CreateProject(ProjectCreate projectCreate, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<ProjectCodeResponse> localVarResponse = CreateProjectWithHttpInfo(projectCreate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create new project This method is used to create a new project through API. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ProjectCodeResponse</returns>
        public Qase.Client.Client.ApiResponse<ProjectCodeResponse> CreateProjectWithHttpInfo(ProjectCreate projectCreate, int operationIndex = 0)
        {
            // verify the required parameter 'projectCreate' is set
            if (projectCreate == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'projectCreate' when calling ProjectsApi->CreateProject");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = projectCreate;

            localVarRequestOptions.Operation = "ProjectsApi.CreateProject";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ProjectCodeResponse>("/project", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateProject", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create new project This method is used to create a new project through API. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProjectCodeResponse</returns>
        public async System.Threading.Tasks.Task<ProjectCodeResponse> CreateProjectAsync(ProjectCreate projectCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<ProjectCodeResponse> localVarResponse = await CreateProjectWithHttpInfoAsync(projectCreate, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create new project This method is used to create a new project through API. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProjectCodeResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<ProjectCodeResponse>> CreateProjectWithHttpInfoAsync(ProjectCreate projectCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'projectCreate' is set
            if (projectCreate == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'projectCreate' when calling ProjectsApi->CreateProject");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = projectCreate;

            localVarRequestOptions.Operation = "ProjectsApi.CreateProject";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ProjectCodeResponse>("/project", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateProject", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Project by code This method allows to delete a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BaseResponse</returns>
        public BaseResponse DeleteProject(string code, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<BaseResponse> localVarResponse = DeleteProjectWithHttpInfo(code);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Project by code This method allows to delete a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BaseResponse</returns>
        public Qase.Client.Client.ApiResponse<BaseResponse> DeleteProjectWithHttpInfo(string code, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ProjectsApi->DeleteProject");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter

            localVarRequestOptions.Operation = "ProjectsApi.DeleteProject";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<BaseResponse>("/project/{code}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteProject", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Project by code This method allows to delete a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BaseResponse</returns>
        public async System.Threading.Tasks.Task<BaseResponse> DeleteProjectAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<BaseResponse> localVarResponse = await DeleteProjectWithHttpInfoAsync(code, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Project by code This method allows to delete a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BaseResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<BaseResponse>> DeleteProjectWithHttpInfoAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ProjectsApi->DeleteProject");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter

            localVarRequestOptions.Operation = "ProjectsApi.DeleteProject";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<BaseResponse>("/project/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteProject", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Project by code This method allows to retrieve a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ProjectResponse</returns>
        public ProjectResponse GetProject(string code, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<ProjectResponse> localVarResponse = GetProjectWithHttpInfo(code);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Project by code This method allows to retrieve a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ProjectResponse</returns>
        public Qase.Client.Client.ApiResponse<ProjectResponse> GetProjectWithHttpInfo(string code, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ProjectsApi->GetProject");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter

            localVarRequestOptions.Operation = "ProjectsApi.GetProject";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ProjectResponse>("/project/{code}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProject", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Project by code This method allows to retrieve a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProjectResponse</returns>
        public async System.Threading.Tasks.Task<ProjectResponse> GetProjectAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<ProjectResponse> localVarResponse = await GetProjectWithHttpInfoAsync(code, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Project by code This method allows to retrieve a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProjectResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<ProjectResponse>> GetProjectWithHttpInfoAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ProjectsApi->GetProject");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter

            localVarRequestOptions.Operation = "ProjectsApi.GetProject";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ProjectResponse>("/project/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProject", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get All Projects This method allows to retrieve all projects available for your account. You can limit and offset params to paginate. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ProjectListResponse</returns>
        public ProjectListResponse GetProjects(int? limit = default(int?), int? offset = default(int?), int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<ProjectListResponse> localVarResponse = GetProjectsWithHttpInfo(limit, offset);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get All Projects This method allows to retrieve all projects available for your account. You can limit and offset params to paginate. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ProjectListResponse</returns>
        public Qase.Client.Client.ApiResponse<ProjectListResponse> GetProjectsWithHttpInfo(int? limit = default(int?), int? offset = default(int?), int operationIndex = 0)
        {
            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }

            localVarRequestOptions.Operation = "ProjectsApi.GetProjects";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ProjectListResponse>("/project", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProjects", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get All Projects This method allows to retrieve all projects available for your account. You can limit and offset params to paginate. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProjectListResponse</returns>
        public async System.Threading.Tasks.Task<ProjectListResponse> GetProjectsAsync(int? limit = default(int?), int? offset = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<ProjectListResponse> localVarResponse = await GetProjectsWithHttpInfoAsync(limit, offset, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get All Projects This method allows to retrieve all projects available for your account. You can limit and offset params to paginate. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProjectListResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<ProjectListResponse>> GetProjectsWithHttpInfoAsync(int? limit = default(int?), int? offset = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }

            localVarRequestOptions.Operation = "ProjectsApi.GetProjects";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ProjectListResponse>("/project", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProjects", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Grant access to project by code This method allows to grant access to a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BaseResponse</returns>
        public BaseResponse GrantAccessToProject(string code, ProjectAccess projectAccess, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<BaseResponse> localVarResponse = GrantAccessToProjectWithHttpInfo(code, projectAccess);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Grant access to project by code This method allows to grant access to a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BaseResponse</returns>
        public Qase.Client.Client.ApiResponse<BaseResponse> GrantAccessToProjectWithHttpInfo(string code, ProjectAccess projectAccess, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ProjectsApi->GrantAccessToProject");
            }

            // verify the required parameter 'projectAccess' is set
            if (projectAccess == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'projectAccess' when calling ProjectsApi->GrantAccessToProject");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = projectAccess;

            localVarRequestOptions.Operation = "ProjectsApi.GrantAccessToProject";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BaseResponse>("/project/{code}/access", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GrantAccessToProject", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Grant access to project by code This method allows to grant access to a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BaseResponse</returns>
        public async System.Threading.Tasks.Task<BaseResponse> GrantAccessToProjectAsync(string code, ProjectAccess projectAccess, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<BaseResponse> localVarResponse = await GrantAccessToProjectWithHttpInfoAsync(code, projectAccess, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Grant access to project by code This method allows to grant access to a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BaseResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<BaseResponse>> GrantAccessToProjectWithHttpInfoAsync(string code, ProjectAccess projectAccess, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ProjectsApi->GrantAccessToProject");
            }

            // verify the required parameter 'projectAccess' is set
            if (projectAccess == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'projectAccess' when calling ProjectsApi->GrantAccessToProject");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = projectAccess;

            localVarRequestOptions.Operation = "ProjectsApi.GrantAccessToProject";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BaseResponse>("/project/{code}/access", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GrantAccessToProject", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revoke access to project by code This method allows to revoke access to a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BaseResponse</returns>
        public BaseResponse RevokeAccessToProject(string code, ProjectAccess projectAccess, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<BaseResponse> localVarResponse = RevokeAccessToProjectWithHttpInfo(code, projectAccess);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Revoke access to project by code This method allows to revoke access to a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BaseResponse</returns>
        public Qase.Client.Client.ApiResponse<BaseResponse> RevokeAccessToProjectWithHttpInfo(string code, ProjectAccess projectAccess, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ProjectsApi->RevokeAccessToProject");
            }

            // verify the required parameter 'projectAccess' is set
            if (projectAccess == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'projectAccess' when calling ProjectsApi->RevokeAccessToProject");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = projectAccess;

            localVarRequestOptions.Operation = "ProjectsApi.RevokeAccessToProject";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<BaseResponse>("/project/{code}/access", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RevokeAccessToProject", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revoke access to project by code This method allows to revoke access to a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BaseResponse</returns>
        public async System.Threading.Tasks.Task<BaseResponse> RevokeAccessToProjectAsync(string code, ProjectAccess projectAccess, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<BaseResponse> localVarResponse = await RevokeAccessToProjectWithHttpInfoAsync(code, projectAccess, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Revoke access to project by code This method allows to revoke access to a specific project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="projectAccess"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BaseResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<BaseResponse>> RevokeAccessToProjectWithHttpInfoAsync(string code, ProjectAccess projectAccess, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling ProjectsApi->RevokeAccessToProject");
            }

            // verify the required parameter 'projectAccess' is set
            if (projectAccess == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'projectAccess' when calling ProjectsApi->RevokeAccessToProject");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = projectAccess;

            localVarRequestOptions.Operation = "ProjectsApi.RevokeAccessToProject";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<BaseResponse>("/project/{code}/access", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RevokeAccessToProject", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
