/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Qase.Client.Client;
using Qase.Client.Model;

namespace Qase.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRunsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Complete a specific run
        /// </summary>
        /// <remarks>
        /// This method allows to complete a specific run. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BaseResponse</returns>
        BaseResponse CompleteRun(string code, int id, int operationIndex = 0);

        /// <summary>
        /// Complete a specific run
        /// </summary>
        /// <remarks>
        /// This method allows to complete a specific run. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BaseResponse</returns>
        ApiResponse<BaseResponse> CompleteRunWithHttpInfo(string code, int id, int operationIndex = 0);
        /// <summary>
        /// Create a new run
        /// </summary>
        /// <remarks>
        /// This method allows to create a run in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="runCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdResponse</returns>
        IdResponse CreateRun(string code, RunCreate runCreate, int operationIndex = 0);

        /// <summary>
        /// Create a new run
        /// </summary>
        /// <remarks>
        /// This method allows to create a run in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="runCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdResponse</returns>
        ApiResponse<IdResponse> CreateRunWithHttpInfo(string code, RunCreate runCreate, int operationIndex = 0);
        /// <summary>
        /// Delete run
        /// </summary>
        /// <remarks>
        /// This method completely deletes a run from repository. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdResponse</returns>
        IdResponse DeleteRun(string code, int id, int operationIndex = 0);

        /// <summary>
        /// Delete run
        /// </summary>
        /// <remarks>
        /// This method completely deletes a run from repository. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdResponse</returns>
        ApiResponse<IdResponse> DeleteRunWithHttpInfo(string code, int id, int operationIndex = 0);
        /// <summary>
        /// Get a specific run
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve a specific run. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RunResponse</returns>
        RunResponse GetRun(string code, int id, string? include = default(string?), int operationIndex = 0);

        /// <summary>
        /// Get a specific run
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve a specific run. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RunResponse</returns>
        ApiResponse<RunResponse> GetRunWithHttpInfo(string code, int id, string? include = default(string?), int operationIndex = 0);
        /// <summary>
        /// Get all runs
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all runs stored in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search"> (optional)</param>
        /// <param name="status">A list of status values separated by comma. Possible values: in_progress, passed, failed, aborted, active (deprecated), complete (deprecated), abort (deprecated).  (optional)</param>
        /// <param name="milestone"> (optional)</param>
        /// <param name="environment"> (optional)</param>
        /// <param name="fromStartTime"> (optional)</param>
        /// <param name="toStartTime"> (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RunListResponse</returns>
        RunListResponse GetRuns(string code, string? search = default(string?), string? status = default(string?), int? milestone = default(int?), int? environment = default(int?), long? fromStartTime = default(long?), long? toStartTime = default(long?), int? limit = default(int?), int? offset = default(int?), string? include = default(string?), int operationIndex = 0);

        /// <summary>
        /// Get all runs
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all runs stored in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search"> (optional)</param>
        /// <param name="status">A list of status values separated by comma. Possible values: in_progress, passed, failed, aborted, active (deprecated), complete (deprecated), abort (deprecated).  (optional)</param>
        /// <param name="milestone"> (optional)</param>
        /// <param name="environment"> (optional)</param>
        /// <param name="fromStartTime"> (optional)</param>
        /// <param name="toStartTime"> (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RunListResponse</returns>
        ApiResponse<RunListResponse> GetRunsWithHttpInfo(string code, string? search = default(string?), string? status = default(string?), int? milestone = default(int?), int? environment = default(int?), long? fromStartTime = default(long?), long? toStartTime = default(long?), int? limit = default(int?), int? offset = default(int?), string? include = default(string?), int operationIndex = 0);
        /// <summary>
        /// Update publicity of a specific run
        /// </summary>
        /// <remarks>
        /// This method allows to update a publicity of specific run. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="runPublic"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RunPublicResponse</returns>
        RunPublicResponse UpdateRunPublicity(string code, int id, RunPublic runPublic, int operationIndex = 0);

        /// <summary>
        /// Update publicity of a specific run
        /// </summary>
        /// <remarks>
        /// This method allows to update a publicity of specific run. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="runPublic"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RunPublicResponse</returns>
        ApiResponse<RunPublicResponse> UpdateRunPublicityWithHttpInfo(string code, int id, RunPublic runPublic, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRunsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Complete a specific run
        /// </summary>
        /// <remarks>
        /// This method allows to complete a specific run. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BaseResponse</returns>
        System.Threading.Tasks.Task<BaseResponse> CompleteRunAsync(string code, int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Complete a specific run
        /// </summary>
        /// <remarks>
        /// This method allows to complete a specific run. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BaseResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BaseResponse>> CompleteRunWithHttpInfoAsync(string code, int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Create a new run
        /// </summary>
        /// <remarks>
        /// This method allows to create a run in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="runCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdResponse</returns>
        System.Threading.Tasks.Task<IdResponse> CreateRunAsync(string code, RunCreate runCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Create a new run
        /// </summary>
        /// <remarks>
        /// This method allows to create a run in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="runCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<IdResponse>> CreateRunWithHttpInfoAsync(string code, RunCreate runCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Delete run
        /// </summary>
        /// <remarks>
        /// This method completely deletes a run from repository. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdResponse</returns>
        System.Threading.Tasks.Task<IdResponse> DeleteRunAsync(string code, int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Delete run
        /// </summary>
        /// <remarks>
        /// This method completely deletes a run from repository. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<IdResponse>> DeleteRunWithHttpInfoAsync(string code, int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get a specific run
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve a specific run. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RunResponse</returns>
        System.Threading.Tasks.Task<RunResponse> GetRunAsync(string code, int id, string? include = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get a specific run
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve a specific run. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RunResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RunResponse>> GetRunWithHttpInfoAsync(string code, int id, string? include = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get all runs
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all runs stored in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search"> (optional)</param>
        /// <param name="status">A list of status values separated by comma. Possible values: in_progress, passed, failed, aborted, active (deprecated), complete (deprecated), abort (deprecated).  (optional)</param>
        /// <param name="milestone"> (optional)</param>
        /// <param name="environment"> (optional)</param>
        /// <param name="fromStartTime"> (optional)</param>
        /// <param name="toStartTime"> (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RunListResponse</returns>
        System.Threading.Tasks.Task<RunListResponse> GetRunsAsync(string code, string? search = default(string?), string? status = default(string?), int? milestone = default(int?), int? environment = default(int?), long? fromStartTime = default(long?), long? toStartTime = default(long?), int? limit = default(int?), int? offset = default(int?), string? include = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get all runs
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all runs stored in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search"> (optional)</param>
        /// <param name="status">A list of status values separated by comma. Possible values: in_progress, passed, failed, aborted, active (deprecated), complete (deprecated), abort (deprecated).  (optional)</param>
        /// <param name="milestone"> (optional)</param>
        /// <param name="environment"> (optional)</param>
        /// <param name="fromStartTime"> (optional)</param>
        /// <param name="toStartTime"> (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RunListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RunListResponse>> GetRunsWithHttpInfoAsync(string code, string? search = default(string?), string? status = default(string?), int? milestone = default(int?), int? environment = default(int?), long? fromStartTime = default(long?), long? toStartTime = default(long?), int? limit = default(int?), int? offset = default(int?), string? include = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Update publicity of a specific run
        /// </summary>
        /// <remarks>
        /// This method allows to update a publicity of specific run. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="runPublic"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RunPublicResponse</returns>
        System.Threading.Tasks.Task<RunPublicResponse> UpdateRunPublicityAsync(string code, int id, RunPublic runPublic, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Update publicity of a specific run
        /// </summary>
        /// <remarks>
        /// This method allows to update a publicity of specific run. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="runPublic"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RunPublicResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RunPublicResponse>> UpdateRunPublicityWithHttpInfoAsync(string code, int id, RunPublic runPublic, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRunsApi : IRunsApiSync, IRunsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RunsApi : IRunsApi
    {
        private Qase.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RunsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RunsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RunsApi(string basePath)
        {
            this.Configuration = Qase.Client.Client.Configuration.MergeConfigurations(
                Qase.Client.Client.GlobalConfiguration.Instance,
                new Qase.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Qase.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RunsApi(Qase.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Qase.Client.Client.Configuration.MergeConfigurations(
                Qase.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Qase.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RunsApi(Qase.Client.Client.ISynchronousClient client, Qase.Client.Client.IAsynchronousClient asyncClient, Qase.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Qase.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Qase.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Qase.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Qase.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Qase.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Complete a specific run This method allows to complete a specific run. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BaseResponse</returns>
        public BaseResponse CompleteRun(string code, int id, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<BaseResponse> localVarResponse = CompleteRunWithHttpInfo(code, id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Complete a specific run This method allows to complete a specific run. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BaseResponse</returns>
        public Qase.Client.Client.ApiResponse<BaseResponse> CompleteRunWithHttpInfo(string code, int id, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling RunsApi->CompleteRun");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", Qase.Client.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "RunsApi.CompleteRun";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BaseResponse>("/run/{code}/{id}/complete", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CompleteRun", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Complete a specific run This method allows to complete a specific run. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BaseResponse</returns>
        public async System.Threading.Tasks.Task<BaseResponse> CompleteRunAsync(string code, int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<BaseResponse> localVarResponse = await CompleteRunWithHttpInfoAsync(code, id, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Complete a specific run This method allows to complete a specific run. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BaseResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<BaseResponse>> CompleteRunWithHttpInfoAsync(string code, int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling RunsApi->CompleteRun");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", Qase.Client.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "RunsApi.CompleteRun";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BaseResponse>("/run/{code}/{id}/complete", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CompleteRun", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new run This method allows to create a run in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="runCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdResponse</returns>
        public IdResponse CreateRun(string code, RunCreate runCreate, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<IdResponse> localVarResponse = CreateRunWithHttpInfo(code, runCreate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new run This method allows to create a run in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="runCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdResponse</returns>
        public Qase.Client.Client.ApiResponse<IdResponse> CreateRunWithHttpInfo(string code, RunCreate runCreate, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling RunsApi->CreateRun");
            }

            // verify the required parameter 'runCreate' is set
            if (runCreate == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'runCreate' when calling RunsApi->CreateRun");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = runCreate;

            localVarRequestOptions.Operation = "RunsApi.CreateRun";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<IdResponse>("/run/{code}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateRun", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new run This method allows to create a run in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="runCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdResponse</returns>
        public async System.Threading.Tasks.Task<IdResponse> CreateRunAsync(string code, RunCreate runCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<IdResponse> localVarResponse = await CreateRunWithHttpInfoAsync(code, runCreate, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new run This method allows to create a run in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="runCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<IdResponse>> CreateRunWithHttpInfoAsync(string code, RunCreate runCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling RunsApi->CreateRun");
            }

            // verify the required parameter 'runCreate' is set
            if (runCreate == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'runCreate' when calling RunsApi->CreateRun");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = runCreate;

            localVarRequestOptions.Operation = "RunsApi.CreateRun";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<IdResponse>("/run/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateRun", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete run This method completely deletes a run from repository. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdResponse</returns>
        public IdResponse DeleteRun(string code, int id, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<IdResponse> localVarResponse = DeleteRunWithHttpInfo(code, id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete run This method completely deletes a run from repository. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdResponse</returns>
        public Qase.Client.Client.ApiResponse<IdResponse> DeleteRunWithHttpInfo(string code, int id, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling RunsApi->DeleteRun");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", Qase.Client.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "RunsApi.DeleteRun";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<IdResponse>("/run/{code}/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteRun", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete run This method completely deletes a run from repository. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdResponse</returns>
        public async System.Threading.Tasks.Task<IdResponse> DeleteRunAsync(string code, int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<IdResponse> localVarResponse = await DeleteRunWithHttpInfoAsync(code, id, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete run This method completely deletes a run from repository. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<IdResponse>> DeleteRunWithHttpInfoAsync(string code, int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling RunsApi->DeleteRun");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", Qase.Client.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "RunsApi.DeleteRun";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<IdResponse>("/run/{code}/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteRun", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a specific run This method allows to retrieve a specific run. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RunResponse</returns>
        public RunResponse GetRun(string code, int id, string? include = default(string?), int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<RunResponse> localVarResponse = GetRunWithHttpInfo(code, id, include);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a specific run This method allows to retrieve a specific run. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RunResponse</returns>
        public Qase.Client.Client.ApiResponse<RunResponse> GetRunWithHttpInfo(string code, int id, string? include = default(string?), int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling RunsApi->GetRun");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", Qase.Client.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (include != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "include", include));
            }

            localVarRequestOptions.Operation = "RunsApi.GetRun";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<RunResponse>("/run/{code}/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRun", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a specific run This method allows to retrieve a specific run. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RunResponse</returns>
        public async System.Threading.Tasks.Task<RunResponse> GetRunAsync(string code, int id, string? include = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<RunResponse> localVarResponse = await GetRunWithHttpInfoAsync(code, id, include, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a specific run This method allows to retrieve a specific run. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RunResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<RunResponse>> GetRunWithHttpInfoAsync(string code, int id, string? include = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling RunsApi->GetRun");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", Qase.Client.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (include != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "include", include));
            }

            localVarRequestOptions.Operation = "RunsApi.GetRun";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<RunResponse>("/run/{code}/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRun", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all runs This method allows to retrieve all runs stored in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search"> (optional)</param>
        /// <param name="status">A list of status values separated by comma. Possible values: in_progress, passed, failed, aborted, active (deprecated), complete (deprecated), abort (deprecated).  (optional)</param>
        /// <param name="milestone"> (optional)</param>
        /// <param name="environment"> (optional)</param>
        /// <param name="fromStartTime"> (optional)</param>
        /// <param name="toStartTime"> (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RunListResponse</returns>
        public RunListResponse GetRuns(string code, string? search = default(string?), string? status = default(string?), int? milestone = default(int?), int? environment = default(int?), long? fromStartTime = default(long?), long? toStartTime = default(long?), int? limit = default(int?), int? offset = default(int?), string? include = default(string?), int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<RunListResponse> localVarResponse = GetRunsWithHttpInfo(code, search, status, milestone, environment, fromStartTime, toStartTime, limit, offset, include);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all runs This method allows to retrieve all runs stored in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search"> (optional)</param>
        /// <param name="status">A list of status values separated by comma. Possible values: in_progress, passed, failed, aborted, active (deprecated), complete (deprecated), abort (deprecated).  (optional)</param>
        /// <param name="milestone"> (optional)</param>
        /// <param name="environment"> (optional)</param>
        /// <param name="fromStartTime"> (optional)</param>
        /// <param name="toStartTime"> (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RunListResponse</returns>
        public Qase.Client.Client.ApiResponse<RunListResponse> GetRunsWithHttpInfo(string code, string? search = default(string?), string? status = default(string?), int? milestone = default(int?), int? environment = default(int?), long? fromStartTime = default(long?), long? toStartTime = default(long?), int? limit = default(int?), int? offset = default(int?), string? include = default(string?), int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling RunsApi->GetRuns");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            if (search != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "search", search));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (milestone != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "milestone", milestone));
            }
            if (environment != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "environment", environment));
            }
            if (fromStartTime != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "from_start_time", fromStartTime));
            }
            if (toStartTime != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "to_start_time", toStartTime));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (include != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "include", include));
            }

            localVarRequestOptions.Operation = "RunsApi.GetRuns";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<RunListResponse>("/run/{code}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRuns", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all runs This method allows to retrieve all runs stored in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search"> (optional)</param>
        /// <param name="status">A list of status values separated by comma. Possible values: in_progress, passed, failed, aborted, active (deprecated), complete (deprecated), abort (deprecated).  (optional)</param>
        /// <param name="milestone"> (optional)</param>
        /// <param name="environment"> (optional)</param>
        /// <param name="fromStartTime"> (optional)</param>
        /// <param name="toStartTime"> (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RunListResponse</returns>
        public async System.Threading.Tasks.Task<RunListResponse> GetRunsAsync(string code, string? search = default(string?), string? status = default(string?), int? milestone = default(int?), int? environment = default(int?), long? fromStartTime = default(long?), long? toStartTime = default(long?), int? limit = default(int?), int? offset = default(int?), string? include = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<RunListResponse> localVarResponse = await GetRunsWithHttpInfoAsync(code, search, status, milestone, environment, fromStartTime, toStartTime, limit, offset, include, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all runs This method allows to retrieve all runs stored in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search"> (optional)</param>
        /// <param name="status">A list of status values separated by comma. Possible values: in_progress, passed, failed, aborted, active (deprecated), complete (deprecated), abort (deprecated).  (optional)</param>
        /// <param name="milestone"> (optional)</param>
        /// <param name="environment"> (optional)</param>
        /// <param name="fromStartTime"> (optional)</param>
        /// <param name="toStartTime"> (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="include">Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects  (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RunListResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<RunListResponse>> GetRunsWithHttpInfoAsync(string code, string? search = default(string?), string? status = default(string?), int? milestone = default(int?), int? environment = default(int?), long? fromStartTime = default(long?), long? toStartTime = default(long?), int? limit = default(int?), int? offset = default(int?), string? include = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling RunsApi->GetRuns");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            if (search != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "search", search));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (milestone != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "milestone", milestone));
            }
            if (environment != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "environment", environment));
            }
            if (fromStartTime != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "from_start_time", fromStartTime));
            }
            if (toStartTime != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "to_start_time", toStartTime));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (include != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "include", include));
            }

            localVarRequestOptions.Operation = "RunsApi.GetRuns";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<RunListResponse>("/run/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRuns", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update publicity of a specific run This method allows to update a publicity of specific run. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="runPublic"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RunPublicResponse</returns>
        public RunPublicResponse UpdateRunPublicity(string code, int id, RunPublic runPublic, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<RunPublicResponse> localVarResponse = UpdateRunPublicityWithHttpInfo(code, id, runPublic);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update publicity of a specific run This method allows to update a publicity of specific run. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="runPublic"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RunPublicResponse</returns>
        public Qase.Client.Client.ApiResponse<RunPublicResponse> UpdateRunPublicityWithHttpInfo(string code, int id, RunPublic runPublic, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling RunsApi->UpdateRunPublicity");
            }

            // verify the required parameter 'runPublic' is set
            if (runPublic == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'runPublic' when calling RunsApi->UpdateRunPublicity");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", Qase.Client.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = runPublic;

            localVarRequestOptions.Operation = "RunsApi.UpdateRunPublicity";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<RunPublicResponse>("/run/{code}/{id}/public", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateRunPublicity", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update publicity of a specific run This method allows to update a publicity of specific run. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="runPublic"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RunPublicResponse</returns>
        public async System.Threading.Tasks.Task<RunPublicResponse> UpdateRunPublicityAsync(string code, int id, RunPublic runPublic, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<RunPublicResponse> localVarResponse = await UpdateRunPublicityWithHttpInfoAsync(code, id, runPublic, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update publicity of a specific run This method allows to update a publicity of specific run. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="id">Identifier.</param>
        /// <param name="runPublic"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RunPublicResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<RunPublicResponse>> UpdateRunPublicityWithHttpInfoAsync(string code, int id, RunPublic runPublic, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling RunsApi->UpdateRunPublicity");
            }

            // verify the required parameter 'runPublic' is set
            if (runPublic == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'runPublic' when calling RunsApi->UpdateRunPublicity");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", Qase.Client.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = runPublic;

            localVarRequestOptions.Operation = "RunsApi.UpdateRunPublicity";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<RunPublicResponse>("/run/{code}/{id}/public", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateRunPublicity", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
