/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Qase.Client.Client;
using Qase.Client.Model;

namespace Qase.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISharedStepsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a new shared step
        /// </summary>
        /// <remarks>
        /// This method allows to create a shared step in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="sharedStepCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>HashResponse</returns>
        HashResponse CreateSharedStep(string code, SharedStepCreate sharedStepCreate, int operationIndex = 0);

        /// <summary>
        /// Create a new shared step
        /// </summary>
        /// <remarks>
        /// This method allows to create a shared step in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="sharedStepCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of HashResponse</returns>
        ApiResponse<HashResponse> CreateSharedStepWithHttpInfo(string code, SharedStepCreate sharedStepCreate, int operationIndex = 0);
        /// <summary>
        /// Delete shared step
        /// </summary>
        /// <remarks>
        /// This method completely deletes a shared step from repository. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>HashResponse</returns>
        HashResponse DeleteSharedStep(string code, string hash, int operationIndex = 0);

        /// <summary>
        /// Delete shared step
        /// </summary>
        /// <remarks>
        /// This method completely deletes a shared step from repository. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of HashResponse</returns>
        ApiResponse<HashResponse> DeleteSharedStepWithHttpInfo(string code, string hash, int operationIndex = 0);
        /// <summary>
        /// Get a specific shared step
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve a specific shared step. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SharedStepResponse</returns>
        SharedStepResponse GetSharedStep(string code, string hash, int operationIndex = 0);

        /// <summary>
        /// Get a specific shared step
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve a specific shared step. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SharedStepResponse</returns>
        ApiResponse<SharedStepResponse> GetSharedStepWithHttpInfo(string code, string hash, int operationIndex = 0);
        /// <summary>
        /// Get all shared steps
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all shared steps stored in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search">Provide a string that will be used to search by name. (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SharedStepListResponse</returns>
        SharedStepListResponse GetSharedSteps(string code, string? search = default(string?), int? limit = default(int?), int? offset = default(int?), int operationIndex = 0);

        /// <summary>
        /// Get all shared steps
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all shared steps stored in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search">Provide a string that will be used to search by name. (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SharedStepListResponse</returns>
        ApiResponse<SharedStepListResponse> GetSharedStepsWithHttpInfo(string code, string? search = default(string?), int? limit = default(int?), int? offset = default(int?), int operationIndex = 0);
        /// <summary>
        /// Update shared step
        /// </summary>
        /// <remarks>
        /// This method updates a shared step. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="sharedStepUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>HashResponse</returns>
        HashResponse UpdateSharedStep(string code, string hash, SharedStepUpdate sharedStepUpdate, int operationIndex = 0);

        /// <summary>
        /// Update shared step
        /// </summary>
        /// <remarks>
        /// This method updates a shared step. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="sharedStepUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of HashResponse</returns>
        ApiResponse<HashResponse> UpdateSharedStepWithHttpInfo(string code, string hash, SharedStepUpdate sharedStepUpdate, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISharedStepsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create a new shared step
        /// </summary>
        /// <remarks>
        /// This method allows to create a shared step in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="sharedStepCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of HashResponse</returns>
        System.Threading.Tasks.Task<HashResponse> CreateSharedStepAsync(string code, SharedStepCreate sharedStepCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Create a new shared step
        /// </summary>
        /// <remarks>
        /// This method allows to create a shared step in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="sharedStepCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (HashResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<HashResponse>> CreateSharedStepWithHttpInfoAsync(string code, SharedStepCreate sharedStepCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Delete shared step
        /// </summary>
        /// <remarks>
        /// This method completely deletes a shared step from repository. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of HashResponse</returns>
        System.Threading.Tasks.Task<HashResponse> DeleteSharedStepAsync(string code, string hash, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Delete shared step
        /// </summary>
        /// <remarks>
        /// This method completely deletes a shared step from repository. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (HashResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<HashResponse>> DeleteSharedStepWithHttpInfoAsync(string code, string hash, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get a specific shared step
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve a specific shared step. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SharedStepResponse</returns>
        System.Threading.Tasks.Task<SharedStepResponse> GetSharedStepAsync(string code, string hash, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get a specific shared step
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve a specific shared step. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SharedStepResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SharedStepResponse>> GetSharedStepWithHttpInfoAsync(string code, string hash, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get all shared steps
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all shared steps stored in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search">Provide a string that will be used to search by name. (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SharedStepListResponse</returns>
        System.Threading.Tasks.Task<SharedStepListResponse> GetSharedStepsAsync(string code, string? search = default(string?), int? limit = default(int?), int? offset = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get all shared steps
        /// </summary>
        /// <remarks>
        /// This method allows to retrieve all shared steps stored in selected project. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search">Provide a string that will be used to search by name. (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SharedStepListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SharedStepListResponse>> GetSharedStepsWithHttpInfoAsync(string code, string? search = default(string?), int? limit = default(int?), int? offset = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Update shared step
        /// </summary>
        /// <remarks>
        /// This method updates a shared step. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="sharedStepUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of HashResponse</returns>
        System.Threading.Tasks.Task<HashResponse> UpdateSharedStepAsync(string code, string hash, SharedStepUpdate sharedStepUpdate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Update shared step
        /// </summary>
        /// <remarks>
        /// This method updates a shared step. 
        /// </remarks>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="sharedStepUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (HashResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<HashResponse>> UpdateSharedStepWithHttpInfoAsync(string code, string hash, SharedStepUpdate sharedStepUpdate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISharedStepsApi : ISharedStepsApiSync, ISharedStepsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SharedStepsApi : ISharedStepsApi
    {
        private Qase.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SharedStepsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SharedStepsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SharedStepsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SharedStepsApi(string basePath)
        {
            this.Configuration = Qase.Client.Client.Configuration.MergeConfigurations(
                Qase.Client.Client.GlobalConfiguration.Instance,
                new Qase.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Qase.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SharedStepsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SharedStepsApi(Qase.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Qase.Client.Client.Configuration.MergeConfigurations(
                Qase.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Qase.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Qase.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SharedStepsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public SharedStepsApi(Qase.Client.Client.ISynchronousClient client, Qase.Client.Client.IAsynchronousClient asyncClient, Qase.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Qase.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Qase.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Qase.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Qase.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Qase.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create a new shared step This method allows to create a shared step in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="sharedStepCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>HashResponse</returns>
        public HashResponse CreateSharedStep(string code, SharedStepCreate sharedStepCreate, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<HashResponse> localVarResponse = CreateSharedStepWithHttpInfo(code, sharedStepCreate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new shared step This method allows to create a shared step in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="sharedStepCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of HashResponse</returns>
        public Qase.Client.Client.ApiResponse<HashResponse> CreateSharedStepWithHttpInfo(string code, SharedStepCreate sharedStepCreate, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling SharedStepsApi->CreateSharedStep");
            }

            // verify the required parameter 'sharedStepCreate' is set
            if (sharedStepCreate == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'sharedStepCreate' when calling SharedStepsApi->CreateSharedStep");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = sharedStepCreate;

            localVarRequestOptions.Operation = "SharedStepsApi.CreateSharedStep";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<HashResponse>("/shared_step/{code}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateSharedStep", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new shared step This method allows to create a shared step in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="sharedStepCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of HashResponse</returns>
        public async System.Threading.Tasks.Task<HashResponse> CreateSharedStepAsync(string code, SharedStepCreate sharedStepCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<HashResponse> localVarResponse = await CreateSharedStepWithHttpInfoAsync(code, sharedStepCreate, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new shared step This method allows to create a shared step in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="sharedStepCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (HashResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<HashResponse>> CreateSharedStepWithHttpInfoAsync(string code, SharedStepCreate sharedStepCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling SharedStepsApi->CreateSharedStep");
            }

            // verify the required parameter 'sharedStepCreate' is set
            if (sharedStepCreate == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'sharedStepCreate' when calling SharedStepsApi->CreateSharedStep");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = sharedStepCreate;

            localVarRequestOptions.Operation = "SharedStepsApi.CreateSharedStep";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<HashResponse>("/shared_step/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateSharedStep", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete shared step This method completely deletes a shared step from repository. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>HashResponse</returns>
        public HashResponse DeleteSharedStep(string code, string hash, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<HashResponse> localVarResponse = DeleteSharedStepWithHttpInfo(code, hash);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete shared step This method completely deletes a shared step from repository. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of HashResponse</returns>
        public Qase.Client.Client.ApiResponse<HashResponse> DeleteSharedStepWithHttpInfo(string code, string hash, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling SharedStepsApi->DeleteSharedStep");
            }

            // verify the required parameter 'hash' is set
            if (hash == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'hash' when calling SharedStepsApi->DeleteSharedStep");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("hash", Qase.Client.Client.ClientUtils.ParameterToString(hash)); // path parameter

            localVarRequestOptions.Operation = "SharedStepsApi.DeleteSharedStep";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<HashResponse>("/shared_step/{code}/{hash}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteSharedStep", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete shared step This method completely deletes a shared step from repository. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of HashResponse</returns>
        public async System.Threading.Tasks.Task<HashResponse> DeleteSharedStepAsync(string code, string hash, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<HashResponse> localVarResponse = await DeleteSharedStepWithHttpInfoAsync(code, hash, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete shared step This method completely deletes a shared step from repository. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (HashResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<HashResponse>> DeleteSharedStepWithHttpInfoAsync(string code, string hash, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling SharedStepsApi->DeleteSharedStep");
            }

            // verify the required parameter 'hash' is set
            if (hash == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'hash' when calling SharedStepsApi->DeleteSharedStep");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("hash", Qase.Client.Client.ClientUtils.ParameterToString(hash)); // path parameter

            localVarRequestOptions.Operation = "SharedStepsApi.DeleteSharedStep";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<HashResponse>("/shared_step/{code}/{hash}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteSharedStep", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a specific shared step This method allows to retrieve a specific shared step. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SharedStepResponse</returns>
        public SharedStepResponse GetSharedStep(string code, string hash, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<SharedStepResponse> localVarResponse = GetSharedStepWithHttpInfo(code, hash);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a specific shared step This method allows to retrieve a specific shared step. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SharedStepResponse</returns>
        public Qase.Client.Client.ApiResponse<SharedStepResponse> GetSharedStepWithHttpInfo(string code, string hash, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling SharedStepsApi->GetSharedStep");
            }

            // verify the required parameter 'hash' is set
            if (hash == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'hash' when calling SharedStepsApi->GetSharedStep");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("hash", Qase.Client.Client.ClientUtils.ParameterToString(hash)); // path parameter

            localVarRequestOptions.Operation = "SharedStepsApi.GetSharedStep";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<SharedStepResponse>("/shared_step/{code}/{hash}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSharedStep", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a specific shared step This method allows to retrieve a specific shared step. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SharedStepResponse</returns>
        public async System.Threading.Tasks.Task<SharedStepResponse> GetSharedStepAsync(string code, string hash, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<SharedStepResponse> localVarResponse = await GetSharedStepWithHttpInfoAsync(code, hash, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a specific shared step This method allows to retrieve a specific shared step. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SharedStepResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<SharedStepResponse>> GetSharedStepWithHttpInfoAsync(string code, string hash, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling SharedStepsApi->GetSharedStep");
            }

            // verify the required parameter 'hash' is set
            if (hash == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'hash' when calling SharedStepsApi->GetSharedStep");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("hash", Qase.Client.Client.ClientUtils.ParameterToString(hash)); // path parameter

            localVarRequestOptions.Operation = "SharedStepsApi.GetSharedStep";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<SharedStepResponse>("/shared_step/{code}/{hash}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSharedStep", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all shared steps This method allows to retrieve all shared steps stored in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search">Provide a string that will be used to search by name. (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SharedStepListResponse</returns>
        public SharedStepListResponse GetSharedSteps(string code, string? search = default(string?), int? limit = default(int?), int? offset = default(int?), int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<SharedStepListResponse> localVarResponse = GetSharedStepsWithHttpInfo(code, search, limit, offset);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all shared steps This method allows to retrieve all shared steps stored in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search">Provide a string that will be used to search by name. (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SharedStepListResponse</returns>
        public Qase.Client.Client.ApiResponse<SharedStepListResponse> GetSharedStepsWithHttpInfo(string code, string? search = default(string?), int? limit = default(int?), int? offset = default(int?), int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling SharedStepsApi->GetSharedSteps");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            if (search != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "search", search));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }

            localVarRequestOptions.Operation = "SharedStepsApi.GetSharedSteps";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<SharedStepListResponse>("/shared_step/{code}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSharedSteps", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all shared steps This method allows to retrieve all shared steps stored in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search">Provide a string that will be used to search by name. (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SharedStepListResponse</returns>
        public async System.Threading.Tasks.Task<SharedStepListResponse> GetSharedStepsAsync(string code, string? search = default(string?), int? limit = default(int?), int? offset = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<SharedStepListResponse> localVarResponse = await GetSharedStepsWithHttpInfoAsync(code, search, limit, offset, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all shared steps This method allows to retrieve all shared steps stored in selected project. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="search">Provide a string that will be used to search by name. (optional)</param>
        /// <param name="limit">A number of entities in result set. (optional, default to 10)</param>
        /// <param name="offset">How many entities should be skipped. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SharedStepListResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<SharedStepListResponse>> GetSharedStepsWithHttpInfoAsync(string code, string? search = default(string?), int? limit = default(int?), int? offset = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling SharedStepsApi->GetSharedSteps");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            if (search != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "search", search));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(Qase.Client.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }

            localVarRequestOptions.Operation = "SharedStepsApi.GetSharedSteps";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<SharedStepListResponse>("/shared_step/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSharedSteps", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update shared step This method updates a shared step. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="sharedStepUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>HashResponse</returns>
        public HashResponse UpdateSharedStep(string code, string hash, SharedStepUpdate sharedStepUpdate, int operationIndex = 0)
        {
            Qase.Client.Client.ApiResponse<HashResponse> localVarResponse = UpdateSharedStepWithHttpInfo(code, hash, sharedStepUpdate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update shared step This method updates a shared step. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="sharedStepUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of HashResponse</returns>
        public Qase.Client.Client.ApiResponse<HashResponse> UpdateSharedStepWithHttpInfo(string code, string hash, SharedStepUpdate sharedStepUpdate, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling SharedStepsApi->UpdateSharedStep");
            }

            // verify the required parameter 'hash' is set
            if (hash == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'hash' when calling SharedStepsApi->UpdateSharedStep");
            }

            // verify the required parameter 'sharedStepUpdate' is set
            if (sharedStepUpdate == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'sharedStepUpdate' when calling SharedStepsApi->UpdateSharedStep");
            }

            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("hash", Qase.Client.Client.ClientUtils.ParameterToString(hash)); // path parameter
            localVarRequestOptions.Data = sharedStepUpdate;

            localVarRequestOptions.Operation = "SharedStepsApi.UpdateSharedStep";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<HashResponse>("/shared_step/{code}/{hash}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateSharedStep", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update shared step This method updates a shared step. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="sharedStepUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of HashResponse</returns>
        public async System.Threading.Tasks.Task<HashResponse> UpdateSharedStepAsync(string code, string hash, SharedStepUpdate sharedStepUpdate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Qase.Client.Client.ApiResponse<HashResponse> localVarResponse = await UpdateSharedStepWithHttpInfoAsync(code, hash, sharedStepUpdate, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update shared step This method updates a shared step. 
        /// </summary>
        /// <exception cref="Qase.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">Code of project, where to search entities.</param>
        /// <param name="hash">Hash.</param>
        /// <param name="sharedStepUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (HashResponse)</returns>
        public async System.Threading.Tasks.Task<Qase.Client.Client.ApiResponse<HashResponse>> UpdateSharedStepWithHttpInfoAsync(string code, string hash, SharedStepUpdate sharedStepUpdate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'code' when calling SharedStepsApi->UpdateSharedStep");
            }

            // verify the required parameter 'hash' is set
            if (hash == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'hash' when calling SharedStepsApi->UpdateSharedStep");
            }

            // verify the required parameter 'sharedStepUpdate' is set
            if (sharedStepUpdate == null)
            {
                throw new Qase.Client.Client.ApiException(400, "Missing required parameter 'sharedStepUpdate' when calling SharedStepsApi->UpdateSharedStep");
            }


            Qase.Client.Client.RequestOptions localVarRequestOptions = new Qase.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Qase.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Qase.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", Qase.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("hash", Qase.Client.Client.ClientUtils.ParameterToString(hash)); // path parameter
            localVarRequestOptions.Data = sharedStepUpdate;

            localVarRequestOptions.Operation = "SharedStepsApi.UpdateSharedStep";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (TokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Token")))
            {
                localVarRequestOptions.HeaderParameters.Add("Token", this.Configuration.GetApiKeyWithPrefix("Token"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<HashResponse>("/shared_step/{code}/{hash}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateSharedStep", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
